models/Article.php
<?php

namespace app\models;

use Yii;
use yii\db\Expression;
use yii\helpers\Html;

/**
 * This is the model class for table "article".
 *
 * @property integer $id
 * @property string $title
 * @property string $text
 * @property string $created_at
 *
 * @property Comment[] $comments
 */
class Article extends \yii\db\ActiveRecord
{
    public function behaviors()
    {
        return [
            [
                'class' => 'yii\behaviors\TimestampBehavior',
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => null,
                'value' => new Expression('NOW()'),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'article';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            //[['id', 'created_at'], 'required'],
            [['id'], 'integer'],
            [['title'], 'string', 'max' => 255],
            [['text'], 'string'],
            //[['created_at'], 'safe'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'text' => 'Text',
            'created_at' => 'Created At',
        ];
    }

    /**
     * @inheritdoc
     * @return ArticleQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new ArticleQuery(get_called_class());
    }

    public function __toString()
    {
        return nl2br(Html::encode(strip_tags(trim($this->text))));
    }

    public function getComments()
    {
        return $this->hasMany(Comment::className(), ['article_id' => 'id']);
    }
}

controllers/ArticleController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Article;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;
use app\models\Comment;

/**
 * ArticleController implements the CRUD actions for Article model.
 */
class ArticleController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'create' => ['POST'],
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Article models.
     * @return mixed
     */
    public function actionIndex()
    {

        try {
            $dataProvider = new ActiveDataProvider([
                'query' => Article::find()
                    ->with(['comments']),
                'pagination' => [
                    'pageSize' => 5,
                ],
                'sort' => [
                    'defaultOrder' => [
                        'created_at' => SORT_DESC,
                    ],
                ],
            ]);
        } catch (\Exception $e) {
            Yii::$app->session->setFlash('init', 'Выполните установку приложения');
            return $this->redirect(['/']);
        }

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'model' => (new Article),
        ]);
    }

    /**
     * Displays a single Article model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);

        $formModel = new Comment([
            'article_id' => $id,
        ]);

        $dataProvider = new ActiveDataProvider([
            'query' => Comment::find()
                ->where([
                    'article_id' => $id,
                    'comment_id' => null,
                ])
                ->with(['comments']),
            'pagination' => [
                'pageSize' => 3,
            ],
            'sort' => [
                'defaultOrder' => [
                    'created_at' => SORT_ASC,
                ],
            ],
        ]);

        return $this->render('view', [
            'model' => $model,
            'formModel' => $formModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new Article model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;

        $model = new Article();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return ['status' => 'success'];
        } else {
            return ['status' => 'error'];
        }
    }

    /**
     * Updates an existing Article model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     *
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }*/

    /**
     * Deletes an existing Article model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     *
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }*/

    /**
     * Finds the Article model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Article the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Article::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/CommentController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Comment;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;

/**
 * CommentController implements the CRUD actions for Comment model.
 */
class CommentController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
            ],
        ];
    }

    /**
     * Lists all Comment models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Comment::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Comment model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Comment model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;

        $model = new Comment();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return ['status' => 'success'];
        } else {
            return ['status' => 'error'];
        }
    }

    /**
     * Updates an existing Comment model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     *
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }*/

    /**
     * Deletes an existing Comment model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     *
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }*/

    /**
     * Finds the Comment model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Comment the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Comment::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/article/_form.php
<?php

use yii\widgets\Pjax;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Article */
/* @var $form yii\widgets\ActiveForm */
?>

<?php Pjax::begin(); ?>

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'text')->textarea(['rows' => 6]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

<?php Pjax::end(); ?>

views/article/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ArticleSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="article-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'text') ?>

    <?= $form->field($model, 'created_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/article/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Article */

$this->title = 'Create Article';
$this->params['breadcrumbs'][] = ['label' => 'Articles', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="article-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/article/index.php
<?php

use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\widgets\Pjax;
use app\models\Article;
use yii\helpers\Url;
use yii\helpers\StringHelper;

/* @var $model Article */
/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Articles';
$this->params['breadcrumbs'][] = $this->title;
?>

    <div id="articleModal"
         class="modal fade bs-example-modal-lg"
         tabindex="-1"
         role="dialog"
         aria-labelledby="createArticleModalLabel">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button"
                            class="close"
                            data-dismiss="modal"
                            aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title">Create Article</h4>
                </div>
                <div class="modal-body">
                    <?php $form = ActiveForm::begin([
                        'action' => Url::to(['article/create']),
                    ]); ?>
                    <?= $form->field($model, 'title')->textInput() ?>
                    <?= $form->field($model, 'text')->textarea(['rows' => 6]) ?>
                    <?php ActiveForm::end(); ?>
                </div>
                <div class="modal-footer">
                    <button id="articleSave" type="button" class="btn btn-success">Save</button>
                </div>
            </div>
        </div>
    </div>

<?php $pjax = Pjax::begin(); ?>

    <div class="row">
        <div class="col-xs-9">
            <?php if ($dataProvider->count): ?>
                <?= \yii\widgets\LinkPager::widget([
                    'pagination' => $dataProvider->pagination,
                    'firstPageLabel' => "&laquo;&laquo;",
                    'lastPageLabel' => "&raquo;&raquo;",
                ]) ?>
            <?php else: ?>
                <p class="lead" style="margin: 20px 0;">No articles yet</p>
            <?php endif; ?>
        </div>
        <div class="col-xs-3">
            <button type="button"
                    class="btn btn-success pull-right"
                    data-toggle="modal"
                    data-target=".bs-example-modal-lg"
                    style="margin: 20px 0;">Create Article
            </button>
        </div>
    </div>

<?php /** @var Article $data */
foreach ($dataProvider->models as $data): ?>
    <div class="panel panel-success">
        <div class="panel-heading">
            <div class="row">
                <div class="col-xs-9">
                    <?= $data->title ? Html::encode($data->title) : StringHelper::truncateWords($data, 10) ?>
                </div>
                <div class="col-xs-3">
                    <div class="pull-right">
                        <?= Yii::$app->formatter->asDatetime($data->created_at) ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel-body">
            <?= StringHelper::truncateWords($data, 10) ?>
            <div class="row">
                <div class="col-xs-9">
                    <a href="<?= Url::to(['article/view', 'id' => $data->id]) ?>"
                       data-pjax="0"
                       role="button">Read more...</a>
                </div>
                <div class="col-xs-3">
                    <div class="pull-right">
                        <?= (count($data->comments) ?: 'No') . ' comments' ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php endforeach; ?>

<?php Pjax::end(); ?>

<?php $js = <<< JS
$(document).ready(function () {
    var form = $('#{$form->id}');
    var pjaxId = '{$pjax->id}';
    var btn = $('#articleSave');
    var modal = $('#articleModal');

    btn.click(function () {
        $.ajax({
            method: 'POST',
            url: form.attr('action'),
            data: form.serialize(),
            beforeSend: function () {
                btn.prop('disabled', true);
            },
            complete: function () {
                btn.prop('disabled', false);
            }
        })
        .done(function (data, textStatus) {
            if (data.status == textStatus) { // success
                $.pjax.reload('#' + pjaxId);
            }
        })
        .always(function () {
            modal.modal('hide');
        });
    });
});
JS;

$this->registerJs($js);

views/article/index1.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Articles';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="article-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Article', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
<?php Pjax::begin(); ?>    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'id',
            'text:ntext',
            'created_at',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
<?php Pjax::end(); ?></div>

views/article/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Article */

$this->title = 'Update Article: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Articles', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="article-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/article/view.php
<?php

use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\widgets\Pjax;
use app\models\Article;
use app\models\Comment;
use yii\helpers\Url;
use yii\helpers\StringHelper;
use yii\captcha\Captcha;

/* @var $model Article */
/* @var $formModel Comment */
/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = ($model->title ? Html::encode($model->title) : StringHelper::truncateWords($model, 10));
$this->params['breadcrumbs'][] = ['label' => 'Articles', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
    <!--Модальное окно с формой добавления коммента.
    При открытии в скрытое поле подставляется ID коммента, который нужно прокомментировать.
    При закрытии окна сбрасываются ошибки валидации.
    При успешном добавлении коммента очищаются текстовые поля.-->
    <div id="commentModal"
         class="modal fade bs-example-modal-lg"
         tabindex="-1"
         role="dialog"
         aria-labelledby="createCommentModalLabel">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button"
                            class="close"
                            data-dismiss="modal"
                            aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title">Create Comment</h4>
                </div>
                <?php $form = ActiveForm::begin([
                    'action' => Url::to(['comment/create']),
                ]); ?>
                <div class="modal-body">
                    <?= $form->field($formModel, 'article_id')->hiddenInput()->label(false) ?>
                    <?= $form->field($formModel, 'comment_id')->hiddenInput(['disabled' => 'disabled'])->label(false) ?>
                    <?= $form->field($formModel, 'name')->textInput() ?>
                    <?= $form->field($formModel, 'email')->textInput() ?>
                    <?= $form->field($formModel, 'text')->textarea(['rows' => 6]) ?>
                    <?= $form->field($formModel, 'captcha')->widget(Captcha::className()) ?>
                </div>
                <div class="modal-footer">
                    <button id="commentSave" type="submit" class="btn btn-success">Save</button>
                </div>
                <?php ActiveForm::end(); ?>
            </div>
        </div>
    </div>

    <!--Контейнер отображения статьи.
    Если не задан заголовок, обрезаем статью до 10-ти слов.-->
    <div class="panel panel-success">
        <div class="panel-heading">
            <div class="row">
                <div class="col-xs-9">
                    <?= $this->title ?>
                </div>
                <div class="col-xs-3">
                    <div class="pull-right">
                        <?= Yii::$app->formatter->asDatetime($model->created_at) ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel-body">
            <?= $model ?>
        </div>
    </div>

<?php $pjax = Pjax::begin(); ?>

    <div class="row">
        <div class="col-xs-9">
            <?php if ($dataProvider->count): ?>
                <?= \yii\widgets\LinkPager::widget([
                    'pagination' => $dataProvider->pagination,
                    'firstPageLabel' => "&laquo;&laquo;",
                    'lastPageLabel' => "&raquo;&raquo;",
                ]) ?>
            <?php else: ?>
                <p class="lead" style="margin: 20px 0;">No comments yet</p>
            <?php endif; ?>
        </div>
        <div class="col-xs-3">
            <button type="button"
                    class="btn btn-success pull-right"
                    data-toggle="modal"
                    data-target=".bs-example-modal-lg"
                    style="margin: 20px 0;">Add comment
            </button>
        </div>
    </div>

<?php /** @var Comment $data */
foreach ($dataProvider->models as $data): ?>
    <div class="panel panel-primary">
        <div class="panel-heading">
            <div class="row">
                <div class="col-xs-9">
                    <?= vsprintf('%s (%s)', [
                        Html::encode($data->name),
                        Html::encode($data->email),
                    ]) ?>
                </div>
                <div class="col-xs-3">
                    <div class="pull-right">
                        <?= Yii::$app->formatter->asDatetime($data->created_at) ?>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel-body">
            <?= $data ?>
        </div>
        <div class="panel-footer">
            <div class="row">
                <div class="col-xs-12">
                    <button type="button"
                            class="btn btn-primary pull-right"
                            data-toggle="modal"
                            data-comment_id="<?= $data->id ?>"
                            data-target=".bs-example-modal-lg">comment
                    </button>
                </div>
                <div class="col-xs-11 col-xs-offset-1" style="margin-top: 10px;">

                    <!--Под основным комментом выводим ответы других пользователей на него.-->
                    <?php if (count($data->comments)):
                        /** @var Comment $data1 */
                        foreach ($data->comments as $data1): ?>
                            <div class="panel panel-info">
                                <div class="panel-heading">
                                    <div class="row">
                                        <div class="col-xs-9">
                                            <?= vsprintf('%s (%s)', [
                                                Html::encode($data1->name),
                                                Html::encode($data1->email),
                                            ]) ?>
                                        </div>
                                        <div class="col-xs-3">
                                            <div class="pull-right">
                                                <?= Yii::$app->formatter->asDatetime($data1->created_at) ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="panel-body">
                                    <?= $data1 ?>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    <?php endif; ?>

                </div>
            </div>
        </div>
    </div>
<?php endforeach; ?>

<?php Pjax::end(); ?>

<?php $js = <<< JS
$(document).ready(function () {
    var form = $('#{$form->id}');
    var pjaxId = '{$pjax->id}';
    var btn = $('#commentSave');
    var modal = $('#commentModal');
    var commentId = $('#comment-comment_id');
    var yiiData = form.yiiActiveForm('data');

    form.submit(function (event) {
        // По сабмиту формы отправляем данные AJAX-ом, закрываем модальное окно, и обновляем список комментов.
        if (yiiData.validated) {
            $.ajax({
                method: 'POST',
                url: form.attr('action'),
                data: form.serialize(),
                beforeSend: function () {
                    btn.prop('disabled', true);
                },
                complete: function () {
                    btn.prop('disabled', false);
                    yiiData.validated = false;
                }
            })
            .done(function (data, textStatus) {
                if (data.status == textStatus) { // success
                    $.pjax.reload('#' + pjaxId);
                    $('#comment-name, #comment-email, #comment-text, #comment-captcha', form).val('');
                    $('#comment-captcha-image').click();
                }
            })
            .always(function () {
                modal.modal('hide');
            });
        }

        event.preventDefault();
    });

    modal.on('hide.bs.modal', function (e) {
        form.yiiActiveForm('resetForm');
        commentId.prop('disabled', true);
        commentId.val('');
    });
    modal.on('show.bs.modal', function (e) {
        var comment_id = $(e.relatedTarget).data('comment_id');

        if (comment_id) {
            commentId.prop('disabled', false);
            commentId.val(comment_id);
        }
    });

    // Поиск и подмена "на лету" URL-ов на кликабельные ссылки
    var regexp = /http[s]?:\/\/\S+/g;
    var extractLinks = function () {
        $('.panel > .panel-body').each(function () {

            var formattedHtml = $(this).html().replace(regexp, function (match) {
                var div = $('<div>');
                var a = $('<a>')
                    .attr('href', match)
                    .attr('target', '_blank')
                    .text(match)
                    .appendTo(div);

                return div.html();
            });

            $(this).html(formattedHtml);
        });
    };

    $(document).on('pjax:complete', function() {
        extractLinks();
    });

    extractLinks();
});
JS;

$this->registerJs($js);

views/article/view1.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Article */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Articles', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="article-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'text:ntext',
            'created_at',
        ],
    ]) ?>

</div>